/*
 * Generated by MTK Drv_CodeGen Version 04.08.0 for MT6573_MP. Copyright MediaTek Inc. (C) 2011.
 * Mon Sep 19 16:44:02 2011
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


